### ISSUE TITLE
jupyter-notebook无法访问

### ISSUE THREAD

**Issue by zzj0311** [piaozhx/DockerMonitor#10]
### 1. 查明问题原因
程序无法跑通有多种原因, 请严格走以下步骤:
1. 提问之前你做过研究吗？你是否说明了自己试过哪些方法解决问题？
2. 你确定这是集群问题吗? 
3. 在提问之前要严格注意这里负责集群维护, 不负责(怎么调参/运行时间慢/不会配环境)

### 2. 复现问题细节
1. 你说明你使用的编程语言/平台了吗， 包括版本号？
2. 如果你的问题包含代码， 你是否已经改写成最小且完整的程序？
3. 如果你的代码不能编译， 问题中是否包含了编译错误信息？ 
运行命令：

```
root@cs280-zhuangzj_node13 ~
# ssh -CNfR 32471:0.0.0.0:32471 admin
```

无报错，且在admin中运行

```
# root @ cs280-zhuangzj_admin in ~ [12:49:59]
$ lsof -i tcp:32471
COMMAND PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
sshd    956 root    6u  IPv4 632430491      0t0  TCP localhost:32471 (LISTEN)
```

可以看到反代已成功建立连接
在node中运行

```
jupyter notebook --allow-root --ip=0.0.0.0 --port=32471
[I 12:52:31.373 NotebookApp] JupyterLab beta preview extension loaded from /root/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 12:52:31.373 NotebookApp] JupyterLab application directory is /root/anaconda3/share/jupyter/lab
[I 12:52:31.379 NotebookApp] Serving notebooks from local directory: /root
[I 12:52:31.379 NotebookApp] 0 active kernels
[I 12:52:31.379 NotebookApp] The Jupyter Notebook is running at:
[I 12:52:31.379 NotebookApp] http://cs280-zhuangzj_node13:32471/
[I 12:52:31.379 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 12:52:31.380 NotebookApp] No web browser found: could not locate runnable browser.

```

正常运行
浏览器打开http://10.19.124.11:32471/，10.19.124.11 拒绝了我们的连接请求。

### 3. 明确自身需求
1. 如果你的程序的输出结果和预期不同， 你是否说明了你的预期结果是什么， 你为什么这么想， 以及程序的实际结果？

**Comment by piaozhx** [comment]
你在admin看一下`netstat -anp | grep 32471` , 开启的网络服务是`0.0.0.0:32471`还是`127.0.0.1:32471`,如果是`127.0.0.1:32471`的话是无法通过`10.19.124.11:32471`访问的

如果出现`127.0.0.1:32471`的话, 尝试如下解决方案:
1. 用vim打开`/etc/ssh/sshd_config`, 添加如下内容
```
GatewayPorts yes
```
2. 重启admin以及你需要开启jupyter的节点(如node13)的ssh服务:
```
service ssh restart
```
然后在尝试一下

**Comment by Rhyssiyan** [comment]
1. 在本机执行ssh -NL 30615:10.10.10.111:30615 clusterContainer(admin)
2. 如果在admin执行,ssh -NL 10.19.124.11:30615:0.0.0.0:30615 node11 最前头要加一个10.19.124.11

**Comment by piaozhx** [comment]
@Rhyssiyan 提供的方法不需要改`sshd_config`

**Comment by zzj0311** [comment]
@piaozhx 能帮忙把容器重置吗。。我好像把ssh玩挂了。。

**Comment by piaozhx** [comment]
@zzj0311  给你重启了, 你怎么弄的还给容器关掉了

**Comment by zzj0311** [comment]
@piaozhx 只是重启了下ssh。。（不是应该还有bash顶着的么。。

**Comment by yanzhh** [comment]
@piaozhx  我也是开启反向代理后，本地输入admin的网址无法连接jupyter。
在admin的/etc/ssh/sshd_config中添加GatewayPorts yes并重启服务后无法ssh连接admin了...

**Comment by piaozhx** [comment]
@yanzhh  你说得对,  容器在关闭sshd之后会自动关闭, 这是由于admin节点设置容器时没有设置自动重启, 目前已修复

**Comment by Lesley96** [comment]
@piaozhx 
尝试该解决方案后开启的网络服务还是`127.0.0.1:32471`， 打开浏览器后10.19.124.11拒绝了我们的连接请求。

**Comment by piaozhx** [comment]
@Lesley96  你确定添加`GatewayPorts yes` 并重启管理节点以及计算节点的ssh了吗, 注意两个都要重启

**Comment by Lesley96** [comment]
@piaozhx 解决了，之前只重启了计算节点...谢啦
