### ISSUE TITLE
Failed to initialize NVML: Driver/library version mismatch

### ISSUE THREAD

**Issue by Rhyssiyan** [piaozhx/DockerMonitor#12]
* Collaborators: @piaozhx @Rhyssiyan 
* 现象:
  - 有同学发现安装完python-dev,python-tk等库后会报驱动不一致的错误``nvidia-smi``无法使用

* 原因:
    - apt-get运行时最后会执行``ldconfig``，导致动态库链接错误
     - 调用ldconfig在计算节点和管理节点所链接的库不一样,进一步发现396.44的库是由nvidia-docker引入而admin节点是用的docker所以在admin中找不到396.44的库(虽然存在该文件但是是0k)。

* 修复方法:
  
1. 方法一. 
 出现问题后在计算节点执行一次ldconfig

2. 方法二. 
 在计算节点执行:
```
rm /usr/lib/x86_64-linux-gnu/*384*
rm /usr/lib/x86_64-linux-gnu/*387*
cd /usr/lib/x86_64-linux-gnu
tar -cvf ~/nvidia.tar lib*396*
```
在管理节点执行:
```
tar -xvf nvidia.tar -C /usr/lib/x86_64-linux-gnu
```

回到计算节点, 执行
```
ldconfig
```

**Comment by rxqy** [comment]
Ran into the same problem now... don't know if I get lucky, but find a simple solution.
Just run `apt-get update` at compute node solves the problem.
My guess is that apt automatically re-ld to the right nvidia library.

Hope it works for you.

**Comment by Rhyssiyan** [comment]
> Ran into the same problem now... don't know if I get lucky, but find a simple solution.
> Just run `apt-get update` at compute node solves the problem.
> My guess is that apt automatically re-ld to the right nvidia library.
> 
> Hope it works for you.

You're right. The end of ``apt-get`` will call ``ldconfig`` to update the dynamic library links.

**Comment by Rhyssiyan** [comment]
The problem has been solved. Close the issue.
