### ISSUE TITLE
High memory usage in node13

### ISSUE THREAD

**Issue by zzj0311** [piaozhx/DockerMonitor#13]
### 1. 查明问题原因
程序无法跑通有多种原因, 请严格走以下步骤:
1. 提问之前你做过研究吗？你是否说明了自己试过哪些方法解决问题？
2. 你确定这是集群问题吗? 
3. 在提问之前要严格注意这里负责集群维护, 不负责(怎么调参/运行时间慢/不会配环境)
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           251G        245G        3.1G        1.9G        3.0G        2.9G
Swap:          4.0G        4.0G          0B
```
As my code always cost only less than 3g memory, I think that's not my fault, please check, thanks!
### 2. 复现问题细节
1. 你说明你使用的编程语言/平台了吗， 包括版本号？
2. 如果你的问题包含代码， 你是否已经改写成最小且完整的程序？
3. 如果你的代码不能编译， 问题中是否包含了编译错误信息？ 

### 3. 明确自身需求
1. 如果你的程序的输出结果和预期不同， 你是否说明了你的预期结果是什么， 你为什么这么想， 以及程序的实际结果？

**Comment by piaozhx** [comment]
内存是这个节点所有人共享的, 你这个情况就是这个节点的其他人占了很多内存
