### ISSUE TITLE
I wonder if we can log into the host through graphic manner? Like XDMCP or VNC

### ISSUE THREAD

**Issue by HackerSoldier** [piaozhx/DockerMonitor#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rhyssiyan** [comment]
你是想要在使用Linux图形界面吗比如gnome,kde. 现在用的容器是不带图形界面的。

**Comment by HackerSoldier** [comment]
好的，谢谢
