### ISSUE TITLE
problem with cuda and apt-get

### ISSUE THREAD

**Issue by HackerSoldier** [piaozhx/DockerMonitor#15]
不好意思打扰了，有点问题实在找不到解决方法，向您求助。
问题的起源是这样的：
1-我安装Numba后，运行程序一直提示出错，网上有提及到说Numba不支持CUDA 9 ，因此我打算安装CUDA 8
2-我从Nvidia官网下载了8.0版本的network版的deb文件，按照教程安装，截图见文件里面：
 2-1 dpkg -i ~/...(文件名太长，这里不写了).deb，这步挺正常的
 2-2 apt-get update，这步也很正常
 2-3 apt-get install cuda
       提示有两个packages have unmet dependencies：
       cuda: Depends: cuda-10-0 (>=10.0.130) but it is not going to be installed
       jdk-11.0.2: Depends:libasound2 (这个应该是和CUDA无关的)
       于是我在2-4试图用apt-get -f install进行修复 
 2-4 apt-get -f install，似乎正常
 2-5 我再次执行apt-get install cuda命令，运行一段时间后，最后报错了，报错信息如下：
       Errors were encountered while processing:
       /var/cache/apt/archives/libcuda1-410_410.79-0ubuntu1_amd64.deb
       /var/cache/apt/archives/nvidia-opencl-icd-410_410.79-0ubuntu1_amd64.deb
      E: Sub-process /usr/bin/dpkg returned an error code (1)
      W: Operation was interrupted before it could finish
 2-6 我猜想是2-5提示的两个包没装上去，为了验证我的猜想，我重新运行了apt-get install cuda，证实了我的猜想
 2-7 为了装上这两个包，我运行apt-get -f install，结果这两个包无法成功安装，提示：
       Unpacking libcuda1-410 (410.79-0ubuntu1) ...
      dpkg: error processing archive /var/cache/apt/archives/libcuda1-410_410.79-0ubuntu1_amd64.deb (--    unpack):
       unable to make backup link of './usr/lib/x86_64-linux-gnu/libcuda.so.410.79' before installing new version: Invalid cross-device link    
       Preparing to unpack .../nvidia-opencl-icd-410_410.79-0ubuntu1_amd64.deb ...
       Unpacking nvidia-opencl-icd-410 (410.79-0ubuntu1) ...
       dpkg: error processing archive /var/cache/apt/archives/nvidia-opencl-icd-410_410.79 0ubuntu1_amd64.deb (--unpack):
       unable to make backup link of './usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.410.79' before installing     new version: Invalid cross-device link

3-更糟糕的是，现在我的apt-get命令用不了了，不管装什么软件或者卸载软件都会提示我这两个包缺失，但是这两个包始终都装不上去，很无奈
4-我还担心已有的CUDA受到影响会用不了
5-请问这两个包装不上去的原因是什么呢？难道是因为AI Cluster上说的不能修改Nvidia Driver吗？我该怎么把这两个包装上去？
6-或者有什么办法能够把我之前的操作都撤销掉？
十分感谢帮忙，具体截图可以在文件中看到，感谢！期待您的答复！

**Comment by piaozhx** [comment]
你在AI集群的账号是多少? 看你这个情况疑似安装cuda的时候没有仔细看选项说明就把nvidia-driver也装了

**Comment by HackerSoldier** [comment]
好的，谢谢您。我的AI集群账号是gaopf，node17
numba我用Anaconda安装成功了，现在的问题是apt-get命令使用不了，还有我不小心装了新的nvidia driver会不会对显卡使用造成未知的影响呢？
节点上我现在在跑一个CPU的对比实验，希望您帮助处理问题时能留意一下，因为重跑一次要很久。
衷心感谢您的帮助，谢谢！

**Comment by piaozhx** [comment]
1. 你新装的驱动会导致docker无法控制你的容器(比如这个你的账号永远不能添加新权限), 使用上会有什么影响不清楚

2. 我进去大概看了一下, 我不清楚你在装cuda的时候是中途断掉了还是怎么着, 那些包都损坏了, 只要老老实实一个一个删除就可以了, 目前损坏包都被我删除了, 不知道还有没有其他问题

3. 安装cuda的时候有两个非常重要的事情, 一个是要把他提供的选项一个一个看的仔仔细细(90%的人一路yes, 都不看内容), 另一个是虽然出于升级等因素考虑是用ubuntu自带的包管理器来管理会比较方便, 但对于研究型用户这些管理器的使用反而成为了一种负担, 所以**我推荐大家选择用runfile安装, 方便快捷, 傻瓜式操作**

**Comment by HackerSoldier** [comment]
好的，感谢您的帮助，对于造成的麻烦我表示十分抱歉，也感谢你在使用上的建议，谢谢！
