### ISSUE TITLE
problem with node17

### ISSUE THREAD

**Issue by GolferChen** [piaozhx/DockerMonitor#16]
打扰了，Node17出了问题
今天下午我和另一个同学同时在node17上跑程序，刚开始一切正常，直到出现了cuda.driver.error: can't allocate 233.5M from device: cuda out of memory
但是我的程序还是运行完了（这很奇怪，因为和以前OOM错误的报错方式不一样）
我以为只是偶然现象，所以再次运行一个程序，还是报了同样的错误，因此我按ctrl c取消了程序的运行
然后问题就来了，17节点登不上去了，一直显示 connect to host 10.10.10.117 port 22259 connection refused
而且 GPU Status上node 17的状态一直不变，所有进程还在，时间也没更新
请问这种情况是不是这个节点或者容器挂掉了，脱离了docker的控制？

**Comment by piaozhx** [comment]
node17服务器遇到问题自动重启了, 所有容器自动关闭, 目前已经重新打开了

**Comment by GolferChen** [comment]
好的，谢谢！
