### ISSUE TITLE
###因无法远程连接ssh，申请新容器  ###报错信息：Connection closed by 10.19.124.11 port 22354  ###用户名:guanyh UID:1354

### ISSUE THREAD

**Issue by YohnGuan** [piaozhx/DockerMonitor#20]
### 1. 查明问题原因
程序无法跑通有多种原因, 请严格走以下步骤:
1. 提问之前你做过研究吗？你是否说明了自己试过哪些方法解决问题？
2. 你确定这是集群问题吗? 
3. 在提问之前要严格注意这里负责集群维护, 不负责(怎么调参/运行时间慢/不会配环境)

### 2. 复现问题细节
1. 你说明你使用的编程语言/平台了吗， 包括版本号？
2. 如果你的问题包含代码， 你是否已经改写成最小且完整的程序？
3. 如果你的代码不能编译， 问题中是否包含了编译错误信息？ 

### 3. 明确自身需求
1. 如果你的程序的输出结果和预期不同， 你是否说明了你的预期结果是什么， 你为什么这么想， 以及程序的实际结果？

**Comment by piaozhx** [comment]
我刚才看了一下你的旧容器, 不清楚你干了什么, 整个zsh都崩掉了.
现在给你开了新的guanyh2, 不要再执行危险操作了

**Comment by YohnGuan** [comment]
好的， 非常感谢！

**Comment by YohnGuan** [comment]
好的，非常感谢， 辛苦了！

Zhixin Piao <notifications@github.com> 于2019年5月5日周日 下午10:12写道：
