### ISSUE TITLE
容器CPU核数限制

### ISSUE THREAD

**Issue by HackerSoldier** [piaozhx/DockerMonitor#22]
AI集群的管理员，你们好。我想确认一个疑问：每个容器能使用到的CPU核数是否是有限的，和当初资源申请表上的CPU核数一致？如果是的话，能否申请增加CPU核数（论文ddl）。十分感谢！

**Comment by piaozhx** [comment]
所有容器cpu核数都是没有限制的

**Comment by HackerSoldier** [comment]
好的，谢谢。
