### ISSUE TITLE
服务器更新后出现 Broken pipe

### ISSUE THREAD

**Issue by persistz** [piaozhx/DockerMonitor#23]
在服务器完成迁移更新后，
自己三次（更新：五次）使用过程中，100%出现了packet_write_wait connection to ... broken pipe的情况，
由于场景比较复杂，难以简单复现（例如晚上挂上脚本，第二天来check发现断开连接

想确认一下，是否在这次更新中引入了类似逻辑（用户一段时间未操作便断开连接之类？

**Comment by piaozhx** [comment]
没有类似的逻辑, 你可以检查一下是否开启shadowsocks等代理导致此问题, 或者看看是不是本地的网络中断了?(学校的网络有的时候会自己断掉让你重新验证)

如果无法解决, 建议使用tmux或者screen来跑程序

**Comment by persistz** [comment]
> 没有类似的逻辑, 你可以检查一下是否开启shadowsocks等代理导致此问题, 或者看看是不是本地的网络中断了?(学校的网络有的时候会自己断掉让你重新验证)
> 
> 如果无法解决, 建议使用tmux或者screen来跑程序

OK，感谢回复
我这边网络有脚本在刷新，不过没关系，我本地用其他方式唤醒ssh解决就可以了。
