### ISSUE TITLE
node26节点问题

### ISSUE THREAD

**Issue by YohnGuan** [piaozhx/DockerMonitor#24]
你好！本人可以正常登录26节点，但是运行nvidia-smi和训练模型时总是发生卡死现象，故怀疑和节点显卡有关。请排查

**Comment by YohnGuan** [comment]
目前26节点已经无法通过 ssh node26 登录，报错信息"ssh: connect to host 10.10.10.126 port 22355: No route to host"

**Comment by piaozhx** [comment]
26节点的机器坏掉了, 正在找人修

**Comment by YohnGuan** [comment]
ok 谢谢啦
