### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by GolferChen** [piaozhx/DockerMonitor#30]
Hello, 我登录node15和node23时显示permission denied,但是集群permission页面上显示我是具有这两个节点的权限的（2个月前还能正常登录），因为近期在赶paper ddl, 需要用到，麻烦有时间帮助处理一下，谢谢！
账号是gaopf.

**Comment by ShenhanQian** [comment]
您好，您在这两个节点的容器因为未知原因中断运行了，现已重启。

**Comment by GolferChen** [comment]
好的，谢谢
