### ISSUE TITLE
Request for restarting admin node

### ISSUE THREAD

**Issue by ZiwenZhuang** [piaozhx/DockerMonitor#38]
在9月15号凌晨，我调式代码的时候，所有ssh链接的客户端突然都提示断开连接。
在我尝试重新用ssh登录的时候 ，提示connection refused，但是我能够ping到10.15.89.41这个IP地址

然后，我发现cluster monitor网页也不能访问了。所以至少应该是admin节点出现了问题。

**Comment by piaozhx** [comment]
已恢复
