### ISSUE TITLE
ipython和ssh node13存在问题

### ISSUE THREAD

**Issue by Privilger** [piaozhx/DockerMonitor#8]
### 1. 查明问题原因
程序无法跑通有多种原因, 请严格走以下步骤:
1. 提问之前你做过研究吗？你是否说明了自己试过哪些方法解决问题？
运行pip install jupyter notebook的时候，
出现一个error message：
jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.2 which is incompatible.
然后出现ipyhon打不开的问题
发现是版本不匹配问题，于是搜到安装低版本的 prompt-toolkit
pip install 'prompt-toolkit==1.0.15'
ipyhon成功打开，并生成密钥，配置jupyter notebook的配置文件
接着ssh node13，报错：
ssh: connect to host 10.10.10.113 port 22220: Connection refused
这里是问题所在，当我还未pip install 'prompt-toolkit==1.0.15'的时候，是可以ssh node13的。
所以推测ipython要求的prompt-toolkit较低，但是低版本的prompt-toolkit不满足ssh node13的要求

2. 你确定这是集群问题吗? 
确定，因为试过其他同学的账号，在pip install jupyter notebook的时候也报相同的错误
3. 在提问之前要严格注意这里负责集群维护, 不负责(怎么调参/运行时间慢/不会配环境)

### 2. 复现问题细节
1. 你说明你使用的编程语言/平台了吗， 包括版本号？
2. 如果你的问题包含代码， 你是否已经改写成最小且完整的程序？
3. 如果你的代码不能编译， 问题中是否包含了编译错误信息？ 

### 3. 明确自身需求
1. 如果你的程序的输出结果和预期不同， 你是否说明了你的预期结果是什么， 你为什么这么想， 以及程序的实际结果？
按照容器配置的教程步骤走，发现错误，是不是软件更新了之后，教程有不适配的情况~

**Comment by piaozhx** [comment]
1. ipython的问题需要低版本prompt-toolkit的问题应该通过升级ipython到高版本解决, 这样能同时兼容jupyter和ipython对于prompt-toolkit的需求了:
```
pip install ipython --upgrade
```

2. ssh node13无法使用这一点很奇怪, 你能提供你在AI集群的用户名吗, 我检查一下

**Comment by Privilger** [comment]
1. 好的我试一下

2. 用户名是：cs280-zhangyzh1

**Comment by Privilger** [comment]
1. 果然upgrade之后就可以了

2. 用户名是：cs280-zhangyzh1

**Comment by Privilger** [comment]
1. 果然upgrade之后就可以了，Thanks♪(･ω･)ﾉ

2. 用户名是：cs280-zhangyzh1

**Comment by piaozhx** [comment]
node13的问题: 我检查了一下你的权限, 你在AI集群的权限是node25, 之前为什么会登上node13...
权限相关的信息可以在[这里](http://10.19.124.11:8899/cs280_permission)看到

**Comment by Privilger** [comment]
我也奇怪...昨晚就是登上了node13(ಥ_ಥ)
